/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SteganoGUI.java
 *
 * Created on 20.03.2012, 15:06:27
 */
package ch.zhaw.swp2.stegano.gui;

import ch.zhaw.swp2.stegano.controller.Controller;
import ch.zhaw.swp2.stegano.controller.IfcUserInterface;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author rest
 */
public class SteganoGUI extends javax.swing.JFrame implements IfcUserInterface{

    private File _baseFile;
    private File _hiddenFile;
    
    /** Creates new form SteganoGUI */
    public SteganoGUI()  {
        
        init();
        initComponents();
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        _jLabelBaseFile = new javax.swing.JLabel();
        _jLabelBaseFilePath = new javax.swing.JLabel();
        _jLabelHiddenFile = new javax.swing.JLabel();
        _jLabelHiddenFilePath = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        _jMenuBar1 = new javax.swing.JMenuBar();
        _jMenuFile = new javax.swing.JMenu();
        _jMenuItemOB = new javax.swing.JMenuItem();
        jMenuItemIH = new javax.swing.JMenuItem();
        _jMenuEdit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stegano");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Hidden in Picture", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1088, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Hidden in Audio", jPanel2);

        _jLabelBaseFile.setText("Basefile-Path:");

        _jLabelBaseFilePath.setText("none");

        _jLabelHiddenFile.setText("Hiddenfile-Path:");

        _jLabelHiddenFilePath.setText("none");

        jButton1.setText("Run Steganographie");

        _jMenuFile.setText("File");

        _jMenuItemOB.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        _jMenuItemOB.setText("Import Basefile");
        _jMenuItemOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importBaseFileActionlistener(evt);
            }
        });
        _jMenuFile.add(_jMenuItemOB);

        jMenuItemIH.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemIH.setText("Import Hiding-File");
        jMenuItemIH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importHiddenFileActionListener(evt);
            }
        });
        _jMenuFile.add(jMenuItemIH);

        _jMenuBar1.add(_jMenuFile);

        _jMenuEdit.setText("Edit");
        _jMenuBar1.add(_jMenuEdit);

        setJMenuBar(_jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_jLabelBaseFile)
                            .addComponent(_jLabelHiddenFile))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_jLabelHiddenFilePath)
                            .addComponent(_jLabelBaseFilePath)))
                    .addComponent(jButton1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1093, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_jLabelBaseFile)
                    .addComponent(_jLabelBaseFilePath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_jLabelHiddenFile)
                    .addComponent(_jLabelHiddenFilePath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void importBaseFileActionlistener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importBaseFileActionlistener

    File file = openFileChooser();
    if(file != null){
        _baseFile = file;
        _jLabelBaseFilePath.setText(_baseFile.getAbsolutePath());        
    }
}//GEN-LAST:event_importBaseFileActionlistener

private void importHiddenFileActionListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importHiddenFileActionListener
    File file = openFileChooser();
    if(file != null){
        _hiddenFile = file;
        _jLabelHiddenFilePath.setText(_hiddenFile.getAbsolutePath());        
    }
}//GEN-LAST:event_importHiddenFileActionListener

    /**
     * @param args the command line arguments
     */
    public static void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SteganoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SteganoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SteganoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SteganoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _jLabelBaseFile;
    private javax.swing.JLabel _jLabelBaseFilePath;
    private javax.swing.JLabel _jLabelHiddenFile;
    private javax.swing.JLabel _jLabelHiddenFilePath;
    private javax.swing.JMenuBar _jMenuBar1;
    private javax.swing.JMenu _jMenuEdit;
    private javax.swing.JMenu _jMenuFile;
    private javax.swing.JMenuItem _jMenuItemOB;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuItem jMenuItemIH;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void displayBaseFile() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void displayModBaseFile() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
    public void setListeners(ActionListener buttonRunStegano){
        jButton1.addActionListener(buttonRunStegano);
    }
    
    private File openFileChooser(){
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setMultiSelectionEnabled(false);
        int returnValue = fileChooser.showOpenDialog(this);
        if(returnValue== JFileChooser.APPROVE_OPTION){
            return fileChooser.getSelectedFile();      
        }
        return null;
    }
}
